# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\merna\Merna\Programming\Python\MRI\MRI 1\mri.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(693, 348)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.btnSheppCreate = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.btnSheppCreate.setFont(font)
        self.btnSheppCreate.setObjectName("btnSheppCreate")
        self.horizontalLayout_13.addWidget(self.btnSheppCreate)
        self.comboSheppSize = QtWidgets.QComboBox(self.centralwidget)
        self.comboSheppSize.setObjectName("comboSheppSize")
        self.comboSheppSize.addItem("")
        self.comboSheppSize.addItem("")
        self.comboSheppSize.addItem("")
        self.comboSheppSize.addItem("")
        self.comboSheppSize.addItem("")
        self.horizontalLayout_13.addWidget(self.comboSheppSize)
        self.horizontalLayout.addLayout(self.horizontalLayout_13)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout_12.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.phantomlbl = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phantomlbl.sizePolicy().hasHeightForWidth())
        self.phantomlbl.setSizePolicy(sizePolicy)
        self.phantomlbl.setMouseTracking(True)
        self.phantomlbl.setFrameShape(QtWidgets.QFrame.Box)
        self.phantomlbl.setText("")
        self.phantomlbl.setObjectName("phantomlbl")
        self.horizontalLayout_14.addWidget(self.phantomlbl)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem3 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem3)
        self.comboViewMode = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboViewMode.sizePolicy().hasHeightForWidth())
        self.comboViewMode.setSizePolicy(sizePolicy)
        self.comboViewMode.setObjectName("comboViewMode")
        self.comboViewMode.addItem("")
        self.comboViewMode.addItem("")
        self.comboViewMode.addItem("")
        self.horizontalLayout_15.addWidget(self.comboViewMode)
        spacerItem4 = QtWidgets.QSpacerItem(90, 17, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 693, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MRI Sequence Simulator"))
        self.btnSheppCreate.setText(_translate("MainWindow", "Shepp-Logan"))
        self.comboSheppSize.setItemText(0, _translate("MainWindow", "Select the size"))
        self.comboSheppSize.setItemText(1, _translate("MainWindow", "16"))
        self.comboSheppSize.setItemText(2, _translate("MainWindow", "32"))
        self.comboSheppSize.setItemText(3, _translate("MainWindow", "64"))
        self.comboSheppSize.setItemText(4, _translate("MainWindow", "128"))
        self.comboViewMode.setItemText(0, _translate("MainWindow", "PD"))
        self.comboViewMode.setItemText(1, _translate("MainWindow", "T1"))
        self.comboViewMode.setItemText(2, _translate("MainWindow", "T2"))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

